### PR TITLE
feat: add files.ls streaming methods

### PR DESCRIPTION
**Pull request by achingbrain**
N.b will not actually do any streaming until https://github.com/ipfs/go-ipfs/pull/5611 is released.

### CODE REVIEW

**Comment by achingbrain** [comment]
Actually, that go PR was for adding streaming to one of the other `ls` commands  😕

**Comment by achingbrain** [comment]
I've added a `--stream` option to the http endpoints for `files.lsReadbleStream` and `files.lsPullStream` that will actually the response as ndjson.

**Comment by alanshaw** [comment]
Currently getting these failures:

```console
1) interface-ipfs-core tests
       .files.lsReadableStream
         should ls directory:
     Uncaught TypeError: stream.on is not a function
      at destroyer (node_modules/pump/index.js:26:10)
      at /Users/alan/Code/protocol-labs/js-ipfs-http-client/node_modules/pump/index.js:70:12
      at Array.map (<anonymous>)
      at pump (node_modules/pump/index.js:67:26)
      at send (src/files-mfs/ls-readable-stream.js:40:7)
      at f (node_modules/once/once.js:25:25)
      at streamToValue (src/utils/stream-to-json-value.js:30:5)
      at concat (src/utils/stream-to-value.js:12:22)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:37:43)
      at finishMaybe (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
      at endWritable (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:638:3)
      at ConcatStream.Writable.end (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:594:41)
      at IncomingMessage.onend (_stream_readable.js:628:10)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  2) interface-ipfs-core tests
       .files.lsReadableStream
         should ls -l directory:
     Uncaught TypeError: stream.on is not a function
      at destroyer (node_modules/pump/index.js:26:10)
      at /Users/alan/Code/protocol-labs/js-ipfs-http-client/node_modules/pump/index.js:70:12
      at Array.map (<anonymous>)
      at pump (node_modules/pump/index.js:67:26)
      at send (src/files-mfs/ls-readable-stream.js:40:7)
      at f (node_modules/once/once.js:25:25)
      at streamToValue (src/utils/stream-to-json-value.js:30:5)
      at concat (src/utils/stream-to-value.js:12:22)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:37:43)
      at finishMaybe (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
      at endWritable (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:638:3)
      at ConcatStream.Writable.end (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:594:41)
      at IncomingMessage.onend (_stream_readable.js:628:10)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  3) interface-ipfs-core tests
       .files.lsPullStream
         should ls directory:
     Uncaught TypeError: stream.on is not a function
      at destroyer (node_modules/pump/index.js:26:10)
      at /Users/alan/Code/protocol-labs/js-ipfs-http-client/node_modules/pump/index.js:70:12
      at Array.map (<anonymous>)
      at pump (node_modules/pump/index.js:67:26)
      at send (src/files-mfs/ls-readable-stream.js:40:7)
      at f (node_modules/once/once.js:25:25)
      at streamToValue (src/utils/stream-to-json-value.js:30:5)
      at concat (src/utils/stream-to-value.js:12:22)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:37:43)
      at finishMaybe (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
      at endWritable (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:638:3)
      at ConcatStream.Writable.end (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:594:41)
      at IncomingMessage.onend (_stream_readable.js:628:10)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  4) interface-ipfs-core tests
       .files.lsPullStream
         should ls -l directory:
     Uncaught TypeError: stream.on is not a function
      at destroyer (node_modules/pump/index.js:26:10)
      at /Users/alan/Code/protocol-labs/js-ipfs-http-client/node_modules/pump/index.js:70:12
      at Array.map (<anonymous>)
      at pump (node_modules/pump/index.js:67:26)
      at send (src/files-mfs/ls-readable-stream.js:40:7)
      at f (node_modules/once/once.js:25:25)
      at streamToValue (src/utils/stream-to-json-value.js:30:5)
      at concat (src/utils/stream-to-value.js:12:22)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:37:43)
      at finishMaybe (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:630:14)
      at endWritable (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:638:3)
      at ConcatStream.Writable.end (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:594:41)
      at IncomingMessage.onend (_stream_readable.js:628:10)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by achingbrain** [comment]
I think you have the wrong version of a module somewhere.  Are you running IPFS with ipfs/js-ipfs#1734 ?  It won't have the streaming `files.ls*` methods otherwise.

**Comment by achingbrain** [comment]
After some discussion what you really wanted here was for the tests to be skipped since `go-ipfs` doesn't support streaming in mfs.ls type commands.

The tests are still useful for running with `js-ipfs` so it'd be a shame to disable them entirely.  I gave up trying to figure out how to disable interface tests for certain implementations and instead changed the handlers to stream the responses if they are given a stream, otherwise to simulate the streaming on a complete response.

Be liberal in what you accept, etc.

**Comment by alanshaw** [comment]
> After some discussion what you really wanted here was for the tests to be skipped since `go-ipfs` doesn't support streaming in mfs.ls type commands.

Yes, apologies for that. Although, I'm glad I didn't specify that now:

> changed the handlers to stream the responses if they are given a stream, otherwise to simulate the streaming on a complete response.

🎉 now it "works" for everybody!

**Pull request merged**
