### PR TITLE
feat(block.rm): add block remove functionality

### LINKED ISSUE #792: block.rm() is missing :(
Was surprised to find that this API was missing. It's in the go ipfs command line but isn't in `js-ipfs-api` and isn't documented in https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/BLOCK.md

### PR DESCRIPTION
**Pull request by Prabhakar-Poudel**
docs: update readme

fixes #792

License: MIT
Signed-off-by: Prabhakar-Poudel <yuvrajzohan@gmail.com>

### CODE REVIEW

**Comment by Prabhakar-Poudel** [comment]
@alanshaw 

> FAIL  ./dist/index.min.js: 243.68KB > maxSize 236KB (gzip)

Bundle size has exceeded the maximum. How can I resolve this?

**Comment by achingbrain** [comment]
`maxSize` is set in [`.aegir.js`](https://github.com/ipfs/js-ipfs-http-client/blob/master/.aegir.js#L8), you may just need to increase that.

**Comment by Prabhakar-Poudel** [comment]
> maxSize is set in .aegir.js, you may just need to increase that.

Will that break other parts of codebase?
And if we keep it increasing every so often, why not have a decent enough of an estimate?
@achingbrain

**Comment by achingbrain** [comment]
This was implemented in #1123.  Sorry, I forgot this was here!

**Pull request closed without merging**
